name: GitHub Actions Demo
on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Ininstall all denpendencies
        run: pip install -r requirements.txt
    